/*
  setCatalog — RevaultAI
  The set library: rooms as data. Walls, floors and furniture are Kenney's CC0
  Furniture Kit pieces, which are modelled at half real size — SCALE doubles
  them so a doorway stands 2 m tall beside our 1.75 m performers. Every piece's
  real footprint is recorded here so the overhead plan can draw it without
  loading anything. Adding a room is one object in SETS.

  Metres, room centred on (0, 0). Positive z is toward the open fourth wall,
  which is left out the way it is on a real set so the camera can get back.
*/

export const SCALE = 2;          // Kenney's kit is built at half size
export const MODEL_PATH = "/models/furniture/";

// file -> real-world [width, depth, height] in metres, after scaling
export const PIECES = {
  bathroomCabinet: [0.86, 0.44, 0.78],
  bathroomMirror: [0.6, 0.28, 0.86],
  bathroomSink: [0.68, 0.58, 1.12],
  bathtub: [2.38, 1.12, 0.84],
  bedDouble: [1.96, 2.28, 0.88],
  bedSingle: [1.96, 2.26, 0.88],
  benchCushion: [0.8, 0.4, 0.92],
  bookcaseClosed: [0.8, 0.5, 1.7],
  bookcaseClosedWide: [1.6, 0.5, 1.58],
  bookcaseOpen: [0.8, 0.5, 1.76],
  books: [0.3, 0.18, 0.2],
  cabinetBedDrawer: [0.54, 0.76, 0.52],
  cabinetTelevision: [1.6, 0.5, 0.62],
  chair: [0.4, 0.4, 0.94],
  chairCushion: [0.4, 0.4, 0.92],
  chairDesk: [0.96, 0.88, 0.84],
  chairRounded: [0.4, 0.4, 0.9],
  coatRack: [0.9, 0.26, 0.56],
  coatRackStanding: [0.54, 0.54, 1.54],
  computerScreen: [0.78, 0.2, 0.58],
  desk: [1.46, 1.12, 0.76],
  deskCorner: [1.94, 2.3, 0.76],
  doorway: [0.98, 0.3, 2.02],
  dryer: [0.78, 0.76, 1.2],
  floorFull: [2.0, 2.0, 0.1],
  hoodModern: [0.86, 0.56, 0.8],
  kitchenBar: [0.86, 0.42, 0.84],
  kitchenCabinet: [0.86, 0.96, 0.9],
  kitchenCabinetDrawer: [0.86, 0.96, 0.9],
  kitchenCabinetUpper: [0.86, 0.46, 0.78],
  kitchenCoffeeMachine: [0.46, 0.54, 0.36],
  kitchenFridge: [0.86, 0.64, 1.84],
  kitchenMicrowave: [0.58, 0.46, 0.36],
  kitchenSink: [0.86, 0.96, 0.98],
  kitchenStove: [0.86, 0.96, 0.9],
  lampRoundFloor: [0.3, 0.36, 1.72],
  lampSquareTable: [0.24, 0.24, 0.58],
  laptop: [0.52, 0.48, 0.32],
  loungeChair: [0.98, 0.82, 0.92],
  loungeDesignChair: [1.46, 0.82, 0.8],
  loungeSofa: [1.96, 0.82, 0.92],
  loungeSofaLong: [1.96, 1.64, 0.92],
  plantSmall1: [0.18, 0.18, 0.28],
  pottedPlant: [0.38, 0.44, 0.54],
  radio: [0.64, 0.2, 0.46],
  rugDoormat: [0.86, 0.48, 0.02],
  rugRectangle: [3.14, 1.84, 0.02],
  rugRound: [1.84, 1.84, 0.02],
  sideTable: [1.06, 0.44, 0.76],
  sideTableDrawers: [1.06, 0.78, 0.76],
  speaker: [0.3, 0.3, 1.28],
  stairs: [3.64, 1.58, 2.68],
  stoolBar: [0.54, 0.46, 0.86],
  table: [1.68, 0.9, 0.66],
  tableCloth: [1.68, 0.9, 0.66],
  tableCoffee: [1.32, 0.8, 0.46],
  tableRound: [1.38, 1.6, 0.74],
  televisionModern: [1.36, 0.26, 0.9],
  toilet: [1.4, 1.18, 0.9],
  trashcan: [0.46, 0.42, 0.86],
  wall: [2.0, 0.1, 2.58],
  wallDoorway: [2.0, 0.18, 2.58],
  wallWindow: [2.0, 0.18, 2.58],
  washer: [0.78, 0.96, 1.0],
};

export const SETS = [
  {
    id: "kitchen",
    name: "Kitchen",
    note: "Counter run, island, table by the window",
    floor: { w: 6, d: 4 },
    walls: [
      { piece: "wall", x: -2.0, z: -2.0, rot: 0 },
      { piece: "wallWindow", x: 0.0, z: -2.0, rot: 0 },
      { piece: "wall", x: 2.0, z: -2.0, rot: 0 },
      { piece: "wall", x: -3.0, z: -1.0, rot: 90 },
      { piece: "wall", x: 3.0, z: -1.0, rot: 90 },
      { piece: "wallDoorway", x: -3.0, z: 1.0, rot: 90 },
      { piece: "wall", x: 3.0, z: 1.0, rot: 90 },
    ],
    props: [
      { id: "kitchenCabinet-0", piece: "kitchenCabinet", label: "the counter", x: -2.1, z: -1.5, rot: 0 },
      { id: "kitchenSink-1", piece: "kitchenSink", label: "the sink", x: -1.2, z: -1.5, rot: 0 },
      { id: "kitchenStove-2", piece: "kitchenStove", label: "the stove", x: -0.3, z: -1.5, rot: 0 },
      { id: "kitchenCabinetDrawer-3", piece: "kitchenCabinetDrawer", label: "the counter", x: 0.6, z: -1.5, rot: 0 },
      { id: "kitchenFridge-4", piece: "kitchenFridge", label: "the fridge", x: 2.3, z: -1.5, rot: 0 },
      { id: "hoodModern-5", piece: "hoodModern", label: "the extractor hood", x: -0.3, z: -1.6, rot: 0, y: 1.5 },
      { id: "kitchenCabinetUpper-6", piece: "kitchenCabinetUpper", label: "the cupboards", x: -2.1, z: -1.7, rot: 0, y: 1.5 },
      { id: "kitchenMicrowave-7", piece: "kitchenMicrowave", label: "the microwave", x: 0.6, z: -1.4, rot: 0, y: 0.9 },
      { id: "kitchenCoffeeMachine-8", piece: "kitchenCoffeeMachine", label: "the coffee machine", x: -2.1, z: -1.4, rot: 0, y: 0.9 },
      { id: "kitchenBar-9", piece: "kitchenBar", label: "the island", x: 0.4, z: 0.2, rot: 0 },
      { id: "stoolBar-10", piece: "stoolBar", label: "a stool", x: -0.2, z: 0.9, rot: 0 },
      { id: "stoolBar-11", piece: "stoolBar", label: "a stool", x: 1.0, z: 0.9, rot: 0 },
      { id: "table-12", piece: "table", label: "the table", x: -1.9, z: 1.3, rot: 0 },
      { id: "chair-13", piece: "chair", label: "a chair", x: -2.6, z: 1.3, rot: 90 },
      { id: "chair-14", piece: "chair", label: "a chair", x: -1.2, z: 1.3, rot: 270 },
      { id: "trashcan-15", piece: "trashcan", label: "the bin", x: 2.4, z: 0.6, rot: 0 },
      { id: "pottedPlant-16", piece: "pottedPlant", label: "the plant", x: 2.5, z: 1.6, rot: 0 },
    ],
  },
  {
    id: "living-room",
    name: "Living room",
    note: "Sofa, coffee table, a window on the long wall",
    floor: { w: 6, d: 5 },
    walls: [
      { piece: "wall", x: -2.0, z: -2.5, rot: 0 },
      { piece: "wallWindow", x: 0.0, z: -2.5, rot: 0 },
      { piece: "wall", x: 2.0, z: -2.5, rot: 0 },
      { piece: "wall", x: -3.0, z: -1.5, rot: 90 },
      { piece: "wall", x: 3.0, z: -1.5, rot: 90 },
      { piece: "wallDoorway", x: -3.0, z: 0.5, rot: 90 },
      { piece: "wall", x: 3.0, z: 0.5, rot: 90 },
    ],
    props: [
      { id: "rugRectangle-0", piece: "rugRectangle", label: "the rug", x: -0.2, z: 0.3, rot: 0 },
      { id: "loungeSofaLong-1", piece: "loungeSofaLong", label: "the sofa", x: -0.4, z: 1.4, rot: 0 },
      { id: "tableCoffee-2", piece: "tableCoffee", label: "the coffee table", x: -0.4, z: 0.2, rot: 0 },
      { id: "loungeChair-3", piece: "loungeChair", label: "the armchair", x: 2.0, z: 0.6, rot: 270 },
      { id: "cabinetTelevision-4", piece: "cabinetTelevision", label: "the television", x: -0.4, z: -1.9, rot: 0 },
      { id: "televisionModern-5", piece: "televisionModern", label: "the television", x: -0.4, z: -1.9, rot: 0, y: 0.62 },
      { id: "bookcaseOpen-6", piece: "bookcaseOpen", label: "the bookshelf", x: -2.6, z: -1.2, rot: 90 },
      { id: "bookcaseClosed-7", piece: "bookcaseClosed", label: "the bookshelf", x: -2.6, z: -0.2, rot: 90 },
      { id: "lampRoundFloor-8", piece: "lampRoundFloor", label: "the standing lamp", x: 2.4, z: -1.5, rot: 0 },
      { id: "sideTable-9", piece: "sideTable", label: "the side table", x: 2.3, z: 1.8, rot: 0 },
      { id: "pottedPlant-10", piece: "pottedPlant", label: "the plant", x: -2.4, z: 1.9, rot: 0 },
      { id: "speaker-11", piece: "speaker", label: "the speaker", x: 1.2, z: -2.0, rot: 0 },
    ],
  },
  {
    id: "bedroom",
    name: "Bedroom",
    note: "Double bed, window, wardrobe wall",
    floor: { w: 5, d: 5 },
    walls: [
      { piece: "wallWindow", x: -1.5, z: -2.5, rot: 0 },
      { piece: "wall", x: 0.5, z: -2.5, rot: 0 },
      { piece: "wall", x: -2.5, z: -1.5, rot: 90 },
      { piece: "wall", x: 2.5, z: -1.5, rot: 90 },
      { piece: "wallDoorway", x: -2.5, z: 0.5, rot: 90 },
      { piece: "wall", x: 2.5, z: 0.5, rot: 90 },
    ],
    props: [
      { id: "bedDouble-0", piece: "bedDouble", label: "the bed", x: -0.3, z: -0.9, rot: 0 },
      { id: "cabinetBedDrawer-1", piece: "cabinetBedDrawer", label: "the bedside table", x: -1.6, z: -1.7, rot: 0 },
      { id: "lampSquareTable-2", piece: "lampSquareTable", label: "the lamp", x: -1.6, z: -1.7, rot: 0, y: 0.9 },
      { id: "cabinetBedDrawer-3", piece: "cabinetBedDrawer", label: "the bedside table", x: 1.0, z: -1.7, rot: 0 },
      { id: "bookcaseClosedWide-4", piece: "bookcaseClosedWide", label: "the wardrobe", x: -1.8, z: 1.9, rot: 0 },
      { id: "bookcaseClosed-5", piece: "bookcaseClosed", label: "the cupboard", x: 2.0, z: -1.5, rot: 90 },
      { id: "rugRound-6", piece: "rugRound", label: "the rug", x: 0.6, z: 1.2, rot: 0 },
      { id: "chairCushion-7", piece: "chairCushion", label: "the chair", x: 2.0, z: 1.3, rot: 270 },
      { id: "coatRackStanding-8", piece: "coatRackStanding", label: "the coat stand", x: -2.2, z: 0.4, rot: 0 },
      { id: "pottedPlant-9", piece: "pottedPlant", label: "the plant", x: 2.2, z: 2.0, rot: 0 },
    ],
  },
  {
    id: "dining-room",
    name: "Dining room",
    note: "Long table, six chairs, sideboard",
    floor: { w: 6, d: 5 },
    walls: [
      { piece: "wall", x: -2.0, z: -2.5, rot: 0 },
      { piece: "wallWindow", x: 0.0, z: -2.5, rot: 0 },
      { piece: "wall", x: 2.0, z: -2.5, rot: 0 },
      { piece: "wall", x: -3.0, z: -1.5, rot: 90 },
      { piece: "wall", x: 3.0, z: -1.5, rot: 90 },
      { piece: "wallDoorway", x: -3.0, z: 0.5, rot: 90 },
      { piece: "wall", x: 3.0, z: 0.5, rot: 90 },
    ],
    props: [
      { id: "rugRectangle-0", piece: "rugRectangle", label: "the rug", x: 0, z: 0.2, rot: 0 },
      { id: "table-1", piece: "table", label: "the table", x: -0.5, z: 0.1, rot: 0 },
      { id: "tableCloth-2", piece: "tableCloth", label: "the table", x: 0.9, z: 0.1, rot: 0 },
      { id: "chair-3", piece: "chair", label: "a chair", x: -1.0, z: -0.9, rot: 0 },
      { id: "chair-4", piece: "chair", label: "a chair", x: 0.2, z: -0.9, rot: 0 },
      { id: "chair-5", piece: "chair", label: "a chair", x: 1.4, z: -0.9, rot: 0 },
      { id: "chair-6", piece: "chair", label: "a chair", x: -1.0, z: 1.1, rot: 180 },
      { id: "chair-7", piece: "chair", label: "a chair", x: 0.2, z: 1.1, rot: 180 },
      { id: "chair-8", piece: "chair", label: "a chair", x: 1.4, z: 1.1, rot: 180 },
      { id: "bookcaseClosedWide-9", piece: "bookcaseClosedWide", label: "the sideboard", x: -1.4, z: -2.0, rot: 0 },
      { id: "pottedPlant-10", piece: "pottedPlant", label: "the plant", x: 2.4, z: -1.8, rot: 0 },
      { id: "lampRoundFloor-11", piece: "lampRoundFloor", label: "the standing lamp", x: 2.5, z: 1.5, rot: 0 },
    ],
  },
  {
    id: "office",
    name: "Home office",
    note: "Desk facing the door, shelves behind",
    floor: { w: 5, d: 4 },
    walls: [
      { piece: "wallWindow", x: -1.5, z: -2.0, rot: 0 },
      { piece: "wall", x: 0.5, z: -2.0, rot: 0 },
      { piece: "wall", x: -2.5, z: -1.0, rot: 90 },
      { piece: "wall", x: 2.5, z: -1.0, rot: 90 },
      { piece: "wallDoorway", x: -2.5, z: 1.0, rot: 90 },
      { piece: "wall", x: 2.5, z: 1.0, rot: 90 },
    ],
    props: [
      { id: "desk-0", piece: "desk", label: "the desk", x: -0.4, z: -0.9, rot: 0 },
      { id: "computerScreen-1", piece: "computerScreen", label: "the monitor", x: -0.4, z: -1.2, rot: 0, y: 0.9 },
      { id: "chairDesk-2", piece: "chairDesk", label: "the desk chair", x: -0.4, z: 0.1, rot: 180 },
      { id: "deskCorner-3", piece: "deskCorner", label: "the side desk", x: 1.6, z: -0.9, rot: 270 },
      { id: "bookcaseOpen-4", piece: "bookcaseOpen", label: "the bookshelf", x: -2.1, z: -1.4, rot: 0 },
      { id: "bookcaseClosed-5", piece: "bookcaseClosed", label: "the bookshelf", x: -1.3, z: -1.4, rot: 0 },
      { id: "chairCushion-6", piece: "chairCushion", label: "the visitor's chair", x: 1.0, z: 1.3, rot: 180 },
      { id: "trashcan-7", piece: "trashcan", label: "the bin", x: -1.5, z: 0.3, rot: 0 },
      { id: "cardboardBoxClosed-8", piece: "cardboardBoxClosed", label: "a box", x: 2.0, z: 1.4, rot: 0 },
      { id: "pottedPlant-9", piece: "pottedPlant", label: "the plant", x: -2.2, z: 1.4, rot: 0 },
    ],
  },
  {
    id: "bathroom",
    name: "Bathroom",
    note: "Bath under the window, sink and mirror",
    floor: { w: 4, d: 3 },
    walls: [
      { piece: "wallWindow", x: -1.0, z: -1.5, rot: 0 },
      { piece: "wall", x: 1.0, z: -1.5, rot: 0 },
      { piece: "wall", x: -2.0, z: -0.5, rot: 90 },
      { piece: "wall", x: 2.0, z: -0.5, rot: 90 },
      { piece: "wallDoorway", x: -2.0, z: 1.5, rot: 90 },
      { piece: "wall", x: 2.0, z: 1.5, rot: 90 },
    ],
    props: [
      { id: "bathtub-0", piece: "bathtub", label: "the bath", x: -0.5, z: -0.9, rot: 0 },
      { id: "toilet-1", piece: "toilet", label: "the toilet", x: 1.4, z: -0.9, rot: 0 },
      { id: "bathroomSink-2", piece: "bathroomSink", label: "the sink", x: -1.5, z: 0.9, rot: 180 },
      { id: "bathroomMirror-3", piece: "bathroomMirror", label: "the mirror", x: -1.5, z: 1.3, rot: 180, y: 1.5 },
      { id: "bathroomCabinet-4", piece: "bathroomCabinet", label: "the cabinet", x: 1.5, z: 1.2, rot: 180, y: 1.5 },
      { id: "rugDoormat-5", piece: "rugDoormat", label: "the mat", x: 0.2, z: 0.8, rot: 0 },
      { id: "washer-6", piece: "washer", label: "the washing machine", x: 1.4, z: 0.6, rot: 0 },
    ],
  },
  {
    id: "hallway",
    name: "Hallway",
    note: "Front door, stairs, coats by the mirror",
    floor: { w: 4, d: 5 },
    walls: [
      { piece: "wallWindow", x: -1.0, z: -2.5, rot: 0 },
      { piece: "wall", x: 1.0, z: -2.5, rot: 0 },
      { piece: "wall", x: -2.0, z: -1.5, rot: 90 },
      { piece: "wall", x: 2.0, z: -1.5, rot: 90 },
      { piece: "wallDoorway", x: -2.0, z: 0.5, rot: 90 },
      { piece: "wall", x: 2.0, z: 0.5, rot: 90 },
    ],
    props: [
      { id: "stairs-0", piece: "stairs", label: "the stairs", x: 1.0, z: -1.2, rot: 270 },
      { id: "doorway-1", piece: "doorway", label: "the front door", x: -1.4, z: 2.2, rot: 0 },
      { id: "rugDoormat-2", piece: "rugDoormat", label: "the doormat", x: -1.4, z: 1.7, rot: 0 },
      { id: "coatRackStanding-3", piece: "coatRackStanding", label: "the coat stand", x: -1.5, z: 0.6, rot: 0 },
      { id: "sideTableDrawers-4", piece: "sideTableDrawers", label: "the hall table", x: 1.4, z: 1.6, rot: 0 },
      { id: "bathroomMirror-5", piece: "bathroomMirror", label: "the mirror", x: -1.9, z: -0.4, rot: 90, y: 1.5 },
      { id: "pottedPlant-6", piece: "pottedPlant", label: "the plant", x: 1.7, z: 0.4, rot: 0 },
    ],
  },
  {
    id: "studio-flat",
    name: "Studio flat",
    note: "Bed, kitchen and sofa in one room",
    floor: { w: 6, d: 5 },
    walls: [
      { piece: "wall", x: -2.0, z: -2.5, rot: 0 },
      { piece: "wallWindow", x: 0.0, z: -2.5, rot: 0 },
      { piece: "wall", x: 2.0, z: -2.5, rot: 0 },
      { piece: "wall", x: -3.0, z: -1.5, rot: 90 },
      { piece: "wall", x: 3.0, z: -1.5, rot: 90 },
      { piece: "wallDoorway", x: -3.0, z: 0.5, rot: 90 },
      { piece: "wall", x: 3.0, z: 0.5, rot: 90 },
    ],
    props: [
      { id: "bedSingle-0", piece: "bedSingle", label: "the bed", x: -2.0, z: -1.0, rot: 90 },
      { id: "cabinetBedDrawer-1", piece: "cabinetBedDrawer", label: "the bedside table", x: -2.4, z: 0.6, rot: 0 },
      { id: "kitchenCabinet-2", piece: "kitchenCabinet", label: "the counter", x: 1.0, z: -1.9, rot: 0 },
      { id: "kitchenSink-3", piece: "kitchenSink", label: "the sink", x: 1.9, z: -1.9, rot: 0 },
      { id: "kitchenStove-4", piece: "kitchenStove", label: "the stove", x: 2.8, z: -1.9, rot: 0 },
      { id: "kitchenFridge-5", piece: "kitchenFridge", label: "the fridge", x: 0.1, z: -1.9, rot: 0 },
      { id: "loungeSofa-6", piece: "loungeSofa", label: "the sofa", x: 0.6, z: 1.4, rot: 0 },
      { id: "tableCoffee-7", piece: "tableCoffee", label: "the coffee table", x: 0.6, z: 0.4, rot: 0 },
      { id: "rugRound-8", piece: "rugRound", label: "the rug", x: 0.6, z: 1.0, rot: 0 },
      { id: "table-9", piece: "table", label: "the table", x: 2.4, z: 0.9, rot: 0 },
      { id: "chair-10", piece: "chair", label: "a chair", x: 2.4, z: 0.0, rot: 0 },
      { id: "lampRoundFloor-11", piece: "lampRoundFloor", label: "the lamp", x: -0.6, z: 1.9, rot: 0 },
      { id: "pottedPlant-12", piece: "pottedPlant", label: "the plant", x: 2.6, z: 2.0, rot: 0 },
    ],
  },
  {
    id: "waiting-room",
    name: "Waiting room",
    note: "Benches facing the door, plants in the corners",
    floor: { w: 5, d: 4 },
    walls: [
      { piece: "wallWindow", x: -1.5, z: -2.0, rot: 0 },
      { piece: "wall", x: 0.5, z: -2.0, rot: 0 },
      { piece: "wall", x: -2.5, z: -1.0, rot: 90 },
      { piece: "wall", x: 2.5, z: -1.0, rot: 90 },
      { piece: "wallDoorway", x: -2.5, z: 1.0, rot: 90 },
      { piece: "wall", x: 2.5, z: 1.0, rot: 90 },
    ],
    props: [
      { id: "benchCushion-0", piece: "benchCushion", label: "a bench", x: -1.6, z: -1.0, rot: 0 },
      { id: "benchCushion-1", piece: "benchCushion", label: "a bench", x: -0.6, z: -1.0, rot: 0 },
      { id: "benchCushion-2", piece: "benchCushion", label: "a bench", x: 0.6, z: -1.0, rot: 0 },
      { id: "benchCushion-3", piece: "benchCushion", label: "a bench", x: 1.6, z: -1.0, rot: 0 },
      { id: "benchCushion-4", piece: "benchCushion", label: "a bench", x: -1.6, z: 1.0, rot: 180 },
      { id: "benchCushion-5", piece: "benchCushion", label: "a bench", x: -0.6, z: 1.0, rot: 180 },
      { id: "sideTable-6", piece: "sideTable", label: "the side table", x: 1.6, z: 1.0, rot: 0 },
      { id: "pottedPlant-7", piece: "pottedPlant", label: "the plant", x: -2.2, z: -1.5, rot: 0 },
      { id: "pottedPlant-8", piece: "pottedPlant", label: "the plant", x: 2.2, z: -1.5, rot: 0 },
      { id: "trashcan-9", piece: "trashcan", label: "the bin", x: 2.2, z: 1.4, rot: 0 },
      { id: "rugDoormat-10", piece: "rugDoormat", label: "the doormat", x: 0, z: 1.8, rot: 0 },
    ],
  },
  {
    id: "cafe",
    name: "Café",
    note: "Counter and stools, tables by the window",
    floor: { w: 6, d: 5 },
    walls: [
      { piece: "wall", x: -2.0, z: -2.5, rot: 0 },
      { piece: "wallWindow", x: 0.0, z: -2.5, rot: 0 },
      { piece: "wall", x: 2.0, z: -2.5, rot: 0 },
      { piece: "wall", x: -3.0, z: -1.5, rot: 90 },
      { piece: "wall", x: 3.0, z: -1.5, rot: 90 },
      { piece: "wallDoorway", x: -3.0, z: 0.5, rot: 90 },
      { piece: "wall", x: 3.0, z: 0.5, rot: 90 },
    ],
    props: [
      { id: "kitchenBar-0", piece: "kitchenBar", label: "the counter", x: -1.4, z: -1.7, rot: 0 },
      { id: "kitchenBar-1", piece: "kitchenBar", label: "the counter", x: -0.5, z: -1.7, rot: 0 },
      { id: "kitchenBar-2", piece: "kitchenBar", label: "the counter", x: 0.4, z: -1.7, rot: 0 },
      { id: "kitchenCoffeeMachine-3", piece: "kitchenCoffeeMachine", label: "the coffee machine", x: -0.5, z: -2.0, rot: 0, y: 0.9 },
      { id: "stoolBar-4", piece: "stoolBar", label: "a stool", x: -1.4, z: -0.8, rot: 0 },
      { id: "stoolBar-5", piece: "stoolBar", label: "a stool", x: -0.5, z: -0.8, rot: 0 },
      { id: "stoolBar-6", piece: "stoolBar", label: "a stool", x: 0.4, z: -0.8, rot: 0 },
      { id: "tableRound-7", piece: "tableRound", label: "a table", x: -1.6, z: 1.2, rot: 0 },
      { id: "chairRounded-8", piece: "chairRounded", label: "a chair", x: -2.4, z: 1.2, rot: 90 },
      { id: "chairRounded-9", piece: "chairRounded", label: "a chair", x: -0.8, z: 1.2, rot: 270 },
      { id: "tableRound-10", piece: "tableRound", label: "a table", x: 1.4, z: 1.2, rot: 0 },
      { id: "chairRounded-11", piece: "chairRounded", label: "a chair", x: 0.6, z: 1.2, rot: 90 },
      { id: "chairRounded-12", piece: "chairRounded", label: "a chair", x: 2.2, z: 1.2, rot: 270 },
      { id: "bookcaseClosedWide-13", piece: "bookcaseClosedWide", label: "the shelves", x: 2.3, z: -1.8, rot: 0 },
      { id: "pottedPlant-14", piece: "pottedPlant", label: "the plant", x: 2.6, z: 2.0, rot: 0 },
    ],
  },
];

export function getSet(id) {
  return SETS.find((s) => s.id === id) ?? null;
}

// Footprint of a placed piece, allowing for how it's turned.
export function pieceSize(placement) {
  const p = PIECES[placement.piece];
  if (!p) return { w: 0.5, d: 0.5, h: 0.5 };
  const turned = placement.rot === 90 || placement.rot === 270;
  return { w: turned ? p[1] : p[0], d: turned ? p[0] : p[1], h: p[2] };
}

// Every model file a room needs, for loading.
export function filesFor(set) {
  const names = new Set();
  for (const w of set?.walls ?? []) names.add(w.piece);
  for (const p of set?.props ?? []) names.add(p.piece);
  return [...names];
}