/*
  setExteriors — RevaultAI
  Six outdoor sets from Kenney's CC0 city, nature and graveyard kits. The
  city kit is modelled far smaller than the others, so every piece carries
  its own scale rather than sharing one number. Sizes here are real metres.
*/

// --- Exteriors: Kenney's city, nature and graveyard kits. The city kit is
// built much smaller than the others, so each piece carries its own scale.
export const EXTERIOR_PIECES = {
  "bench": [1.62, 0.92, 1.06],
  "bench-damaged": [1.82, 0.92, 1.04],
  "building-a": [7.04, 7.52, 10.32],
  "building-c": [7.04, 8.72, 7.12],
  "building-e": [13.12, 8.08, 7.12],
  "building-h": [7.04, 8.08, 10.32],
  "building-k": [16.64, 7.52, 11.76],
  "building-type-a": [10.4, 8.24, 6.64],
  "building-type-c": [10.32, 8.24, 8.24],
  "building-type-j": [10.96, 7.36, 8.32],
  "building-type-k": [7.36, 8.16, 9.2],
  "building-type-p": [9.92, 7.92, 7.36],
  "cross-column": [0.9, 0.9, 2.9],
  "crypt-small": [2.7, 2.8, 2.0],
  "crypt-small-roof": [3.0, 2.88, 1.48],
  "debris": [1.08, 1.1, 0.32],
  "detail-awning-wide": [6.4, 1.2, 3.2],
  "detail-overhang-wide": [8.0, 1.6, 3.2],
  "driveway-long": [2.88, 3.2, 0.08],
  "fence-1x2": [7.04, 3.52, 2.16],
  "fence-1x4": [13.44, 3.52, 2.16],
  "fence_gate": [2.0, 1.0, 0.94],
  "fence_planks": [2.0, 0.2, 0.7],
  "flower_redA": [0.32, 0.36, 0.58],
  "flower_yellowA": [0.32, 0.36, 0.38],
  "grass_large": [0.82, 0.82, 0.5],
  "grave": [1.44, 2.48, 0.22],
  "gravestone-bevel": [0.9, 0.5, 1.06],
  "gravestone-broken": [1.02, 0.78, 0.68],
  "gravestone-cross": [0.9, 0.66, 1.82],
  "gravestone-round": [0.9, 0.5, 1.14],
  "gravestone-wide": [1.7, 0.6, 1.14],
  "ground_grass": [2.0, 2.0, 0.02],
  "ground_pathCorner": [2.0, 2.0, 0.1],
  "ground_pathStraight": [2.0, 2.0, 0.1],
  "iron-fence": [2.0, 0.22, 1.76],
  "iron-fence-border": [2.0, 0.3, 1.76],
  "iron-fence-border-column": [2.0, 0.44, 1.76],
  "iron-fence-border-gate": [2.0, 0.44, 1.52],
  "lantern-candle": [0.48, 0.48, 0.78],
  "lightpost-single": [0.42, 0.92, 2.54],
  "log_large": [2.0, 1.1, 0.84],
  "path-long": [1.6, 3.2, 0.08],
  "path-short": [1.6, 1.6, 0.08],
  "pillar-large": [0.44, 0.44, 2.26],
  "pine": [2.36, 2.66, 4.6],
  "pine-crooked": [2.36, 2.66, 4.22],
  "plant_bushDetailed": [1.2, 1.2, 0.72],
  "plant_bushLarge": [0.74, 0.68, 0.48],
  "road": [6.4, 6.32, 0.64],
  "rock_largeC": [2.12, 2.04, 0.64],
  "rock_smallA": [0.72, 0.72, 0.38],
  "rock_tallC": [0.92, 0.88, 1.56],
  "statue_column": [0.6, 0.6, 2.0],
  "stone-wall": [2.0, 0.4, 1.46],
  "stone-wall-column": [2.0, 0.7, 1.7],
  "stump_old": [0.72, 0.74, 0.54],
  "tent_detailedOpen": [1.74, 1.34, 1.12],
  "tree-large": [1.68, 1.92, 6.16],
  "tree-small": [1.68, 1.92, 4.56],
  "tree_default": [1.52, 1.3, 3.42],
  "tree_oak": [1.28, 1.48, 2.46],
  "tree_pineTallB": [0.78, 0.78, 3.86],
  "tree_small": [0.7, 0.82, 2.22],
  "tree_tall": [0.8, 0.92, 3.38],
  "tree_thin": [1.36, 1.24, 2.98],
  "trunk-long": [1.08, 1.08, 2.0],
};

export const PIECE_META = {
  "bench": { dir: "graveyard", scale: 2.0 },
  "bench-damaged": { dir: "graveyard", scale: 2.0 },
  "building-a": { dir: "commercial", scale: 8.0 },
  "building-c": { dir: "commercial", scale: 8.0 },
  "building-e": { dir: "commercial", scale: 8.0 },
  "building-h": { dir: "commercial", scale: 8.0 },
  "building-k": { dir: "commercial", scale: 8.0 },
  "building-type-a": { dir: "suburban", scale: 8.0 },
  "building-type-c": { dir: "suburban", scale: 8.0 },
  "building-type-j": { dir: "suburban", scale: 8.0 },
  "building-type-k": { dir: "suburban", scale: 8.0 },
  "building-type-p": { dir: "suburban", scale: 8.0 },
  "cross-column": { dir: "graveyard", scale: 2.0 },
  "crypt-small": { dir: "graveyard", scale: 2.0 },
  "crypt-small-roof": { dir: "graveyard", scale: 2.0 },
  "debris": { dir: "graveyard", scale: 2.0 },
  "detail-awning-wide": { dir: "suburban", scale: 8.0 },
  "detail-overhang-wide": { dir: "commercial", scale: 8.0 },
  "driveway-long": { dir: "suburban", scale: 8.0 },
  "fence-1x2": { dir: "suburban", scale: 8.0 },
  "fence-1x4": { dir: "suburban", scale: 8.0 },
  "fence_gate": { dir: "nature", scale: 2.0 },
  "fence_planks": { dir: "nature", scale: 2.0 },
  "flower_redA": { dir: "nature", scale: 2.0 },
  "flower_yellowA": { dir: "nature", scale: 2.0 },
  "grass_large": { dir: "nature", scale: 2.0 },
  "grave": { dir: "graveyard", scale: 2.0 },
  "gravestone-bevel": { dir: "graveyard", scale: 2.0 },
  "gravestone-broken": { dir: "graveyard", scale: 2.0 },
  "gravestone-cross": { dir: "graveyard", scale: 2.0 },
  "gravestone-round": { dir: "graveyard", scale: 2.0 },
  "gravestone-wide": { dir: "graveyard", scale: 2.0 },
  "ground_grass": { dir: "nature", scale: 2.0 },
  "ground_pathCorner": { dir: "nature", scale: 2.0 },
  "ground_pathStraight": { dir: "nature", scale: 2.0 },
  "iron-fence": { dir: "nature", scale: 2.0 },
  "iron-fence-border": { dir: "graveyard", scale: 2.0 },
  "iron-fence-border-column": { dir: "nature", scale: 2.0 },
  "iron-fence-border-gate": { dir: "graveyard", scale: 2.0 },
  "lantern-candle": { dir: "graveyard", scale: 2.0 },
  "lightpost-single": { dir: "commercial", scale: 2.0 },
  "log_large": { dir: "nature", scale: 2.0 },
  "path-long": { dir: "suburban", scale: 8.0 },
  "path-short": { dir: "suburban", scale: 8.0 },
  "pillar-large": { dir: "nature", scale: 2.0 },
  "pine": { dir: "graveyard", scale: 2.0 },
  "pine-crooked": { dir: "graveyard", scale: 2.0 },
  "plant_bushDetailed": { dir: "nature", scale: 2.0 },
  "plant_bushLarge": { dir: "nature", scale: 2.0 },
  "road": { dir: "commercial", scale: 8.0 },
  "rock_largeC": { dir: "nature", scale: 2.0 },
  "rock_smallA": { dir: "nature", scale: 2.0 },
  "rock_tallC": { dir: "nature", scale: 2.0 },
  "statue_column": { dir: "nature", scale: 2.0 },
  "stone-wall": { dir: "graveyard", scale: 2.0 },
  "stone-wall-column": { dir: "nature", scale: 2.0 },
  "stump_old": { dir: "nature", scale: 2.0 },
  "tent_detailedOpen": { dir: "nature", scale: 2.0 },
  "tree-large": { dir: "suburban", scale: 8.0 },
  "tree-small": { dir: "suburban", scale: 8.0 },
  "tree_default": { dir: "nature", scale: 2.0 },
  "tree_oak": { dir: "nature", scale: 2.0 },
  "tree_pineTallB": { dir: "nature", scale: 2.0 },
  "tree_small": { dir: "nature", scale: 2.0 },
  "tree_tall": { dir: "nature", scale: 2.0 },
  "tree_thin": { dir: "nature", scale: 2.0 },
  "trunk-long": { dir: "nature", scale: 2.0 },
};

export const EXTERIORS = [
  {
    id: "street-corner",
    name: "Street corner",
    note: "Shopfronts, a road, light and railings",
    outdoor: true,
    floor: { w: 26, d: 20 },
    walls: [],
    props: [
      { id: "road-0", piece: "road", label: "road", x: -9.0, z: -6, rot: 0 },
      { id: "road-1", piece: "road", label: "road", x: -2.6, z: -6, rot: 0 },
      { id: "road-2", piece: "road", label: "road", x: 3.8, z: -6, rot: 0 },
      { id: "road-3", piece: "road", label: "road", x: 10.2, z: -6, rot: 0 },
      { id: "road-4", piece: "road", label: "road", x: -9.0, z: 0.4, rot: 0 },
      { id: "road-5", piece: "road", label: "road", x: -2.6, z: 0.4, rot: 0 },
      { id: "road-6", piece: "road", label: "road", x: 3.8, z: 0.4, rot: 0 },
      { id: "road-7", piece: "road", label: "road", x: 10.2, z: 0.4, rot: 0 },
      { id: "building-type-c-8", piece: "building-type-c", label: "the corner shop", x: -6, z: -12, rot: 0 },
      { id: "building-a-9", piece: "building-a", label: "the tenement", x: 2, z: -12, rot: 0 },
      { id: "building-type-k-10", piece: "building-type-k", label: "the offices", x: 9, z: -12, rot: 0 },
      { id: "detail-awning-wide-11", piece: "detail-awning-wide", label: "the awning", x: -6, z: -8.6, rot: 0 },
      { id: "lightpost-single-12", piece: "lightpost-single", label: "the street light", x: -2.5, z: -4.5, rot: 0 },
      { id: "lightpost-single-13", piece: "lightpost-single", label: "the street light", x: 8, z: -4.5, rot: 0 },
      { id: "tree-small-14", piece: "tree-small", label: "the street tree", x: 4.5, z: -4.6, rot: 0 },
      { id: "fence-1x4-15", piece: "fence-1x4", label: "the railings", x: -11, z: 4, rot: 0 },
    ],
  },
  {
    id: "alley",
    name: "Alley",
    note: "Two blank walls, a lamp, and nowhere to run",
    outdoor: true,
    floor: { w: 14, d: 16 },
    walls: [],
    props: [
      { id: "building-a-0", piece: "building-a", label: "the left wall", x: -7, z: -4, rot: 90 },
      { id: "building-a-1", piece: "building-a", label: "the left wall", x: -7, z: 4, rot: 90 },
      { id: "building-h-2", piece: "building-h", label: "the right wall", x: 7, z: -4, rot: 270 },
      { id: "building-h-3", piece: "building-h", label: "the right wall", x: 7, z: 4, rot: 270 },
      { id: "road-4", piece: "road", label: "the ground", x: 0, z: -3, rot: 0 },
      { id: "road-5", piece: "road", label: "the ground", x: 0, z: 3.4, rot: 0 },
      { id: "debris-6", piece: "debris", label: "the rubbish", x: -2.4, z: 1.5, rot: 0 },
      { id: "debris-7", piece: "debris", label: "the rubbish", x: 3.1, z: -2.2, rot: 0 },
      { id: "lightpost-single-8", piece: "lightpost-single", label: "the lamp", x: -4.6, z: -4.5, rot: 90 },
      { id: "stump_old-9", piece: "stump_old", label: "the crate", x: 4.2, z: 4.6, rot: 0 },
    ],
  },
  {
    id: "shopfront",
    name: "Shopfront",
    note: "A shop, its awning, and the pavement outside",
    outdoor: true,
    floor: { w: 18, d: 16 },
    walls: [],
    props: [
      { id: "building-type-a-0", piece: "building-type-a", label: "the shop", x: 0, z: -7, rot: 0 },
      { id: "detail-overhang-wide-1", piece: "detail-overhang-wide", label: "the overhang", x: 0, z: -3.6, rot: 0 },
      { id: "road-2", piece: "road", label: "the road", x: 0, z: 4, rot: 0 },
      { id: "road-3", piece: "road", label: "the road", x: 6.4, z: 4, rot: 0 },
      { id: "road-4", piece: "road", label: "the road", x: -6.4, z: 4, rot: 0 },
      { id: "path-long-5", piece: "path-long", label: "the pavement", x: -3, z: 0.4, rot: 0 },
      { id: "path-long-6", piece: "path-long", label: "the pavement", x: 0.2, z: 0.4, rot: 0 },
      { id: "path-long-7", piece: "path-long", label: "the pavement", x: 3.4, z: 0.4, rot: 0 },
      { id: "bench-8", piece: "bench", label: "the bench", x: -4.4, z: 0.6, rot: 0 },
      { id: "tree-small-9", piece: "tree-small", label: "the tree", x: 4.6, z: 0.4, rot: 0 },
      { id: "lightpost-single-10", piece: "lightpost-single", label: "the street light", x: -6.4, z: 0.2, rot: 0 },
    ],
  },
  {
    id: "front-garden",
    name: "Front garden",
    note: "A house, a path to its door, a fence at the pavement",
    outdoor: true,
    floor: { w: 18, d: 14 },
    walls: [],
    props: [
      { id: "building-type-j-0", piece: "building-type-j", label: "the house", x: 0, z: -7.5, rot: 0 },
      { id: "driveway-long-1", piece: "driveway-long", label: "the driveway", x: 4.2, z: -1, rot: 0 },
      { id: "path-long-2", piece: "path-long", label: "the path", x: 0, z: -1.6, rot: 0 },
      { id: "path-long-3", piece: "path-long", label: "the path", x: 0, z: 1.6, rot: 0 },
      { id: "ground_grass-4", piece: "ground_grass", label: "the lawn", x: -4, z: 0, rot: 0 },
      { id: "ground_grass-5", piece: "ground_grass", label: "the lawn", x: -4, z: 2, rot: 0 },
      { id: "ground_grass-6", piece: "ground_grass", label: "the lawn", x: -6, z: 0, rot: 0 },
      { id: "fence-1x4-7", piece: "fence-1x4", label: "the front fence", x: -5, z: 5.4, rot: 0 },
      { id: "fence-1x4-8", piece: "fence-1x4", label: "the front fence", x: 1.7, z: 5.4, rot: 0 },
      { id: "plant_bushDetailed-9", piece: "plant_bushDetailed", label: "the hedge", x: -2.4, z: -3.4, rot: 0 },
      { id: "plant_bushDetailed-10", piece: "plant_bushDetailed", label: "the hedge", x: 2.4, z: -3.4, rot: 0 },
      { id: "tree_small-11", piece: "tree_small", label: "the tree", x: -6, z: -3.4, rot: 0 },
      { id: "flower_redA-12", piece: "flower_redA", label: "the flowerbed", x: -3.4, z: 1.2, rot: 0 },
    ],
  },
  {
    id: "park",
    name: "Park",
    note: "A path through trees, benches either side",
    outdoor: true,
    floor: { w: 20, d: 14 },
    walls: [],
    props: [
      { id: "ground_pathStraight-0", piece: "ground_pathStraight", label: "ground_pathStraight", x: -5, z: 0, rot: 0 },
      { id: "ground_pathStraight-1", piece: "ground_pathStraight", label: "ground_pathStraight", x: -3, z: 0, rot: 0 },
      { id: "ground_pathStraight-2", piece: "ground_pathStraight", label: "ground_pathStraight", x: -1, z: 0, rot: 0 },
      { id: "ground_pathStraight-3", piece: "ground_pathStraight", label: "ground_pathStraight", x: 1, z: 0, rot: 0 },
      { id: "ground_pathStraight-4", piece: "ground_pathStraight", label: "ground_pathStraight", x: 3, z: 0, rot: 0 },
      { id: "ground_pathStraight-5", piece: "ground_pathStraight", label: "ground_pathStraight", x: 5, z: 0, rot: 0 },
      { id: "tree_default-6", piece: "tree_default", label: "the big tree", x: -6, z: -4.5, rot: 0 },
      { id: "tree_oak-7", piece: "tree_oak", label: "the oak", x: 2.5, z: -5, rot: 0 },
      { id: "tree_tall-8", piece: "tree_tall", label: "the poplar", x: 7, z: -3, rot: 0 },
      { id: "tree_thin-9", piece: "tree_thin", label: "the willow", x: -3, z: 5, rot: 0 },
      { id: "bench-10", piece: "bench", label: "the bench", x: -2.5, z: -1.6, rot: 0 },
      { id: "bench-11", piece: "bench", label: "the bench", x: 3.5, z: 1.8, rot: 180 },
      { id: "plant_bushDetailed-12", piece: "plant_bushDetailed", label: "the bushes", x: -7, z: 2.4, rot: 0 },
      { id: "plant_bushLarge-13", piece: "plant_bushLarge", label: "the bushes", x: 5.5, z: 4, rot: 0 },
      { id: "rock_largeC-14", piece: "rock_largeC", label: "the rocks", x: 7.5, z: 4.5, rot: 0 },
      { id: "grass_large-15", piece: "grass_large", label: "the long grass", x: -1, z: 3.2, rot: 0 },
      { id: "lightpost-single-16", piece: "lightpost-single", label: "the park lamp", x: 0.5, z: -1.8, rot: 0 },
      { id: "statue_column-17", piece: "statue_column", label: "the memorial", x: -8, z: -1, rot: 0 },
    ],
  },
  {
    id: "cemetery",
    name: "Cemetery",
    note: "Rows of stones, a crypt, iron railings at the gate",
    outdoor: true,
    floor: { w: 22, d: 16 },
    walls: [],
    props: [
      { id: "gravestone-cross-0", piece: "gravestone-cross", label: "the graves", x: -6.5, z: -4.5, rot: 0 },
      { id: "grave-1", piece: "grave", label: "the graves", x: -6.5, z: -3.2, rot: 0 },
      { id: "gravestone-round-2", piece: "gravestone-round", label: "the graves", x: -4, z: -4.5, rot: 0 },
      { id: "grave-3", piece: "grave", label: "the graves", x: -4, z: -3.2, rot: 0 },
      { id: "gravestone-bevel-4", piece: "gravestone-bevel", label: "the graves", x: -1.5, z: -4.5, rot: 0 },
      { id: "grave-5", piece: "grave", label: "the graves", x: -1.5, z: -3.2, rot: 0 },
      { id: "gravestone-wide-6", piece: "gravestone-wide", label: "the graves", x: 1, z: -4.5, rot: 0 },
      { id: "grave-7", piece: "grave", label: "the graves", x: 1, z: -3.2, rot: 0 },
      { id: "gravestone-broken-8", piece: "gravestone-broken", label: "the graves", x: 3.5, z: -4.5, rot: 0 },
      { id: "grave-9", piece: "grave", label: "the graves", x: 3.5, z: -3.2, rot: 0 },
      { id: "gravestone-round-10", piece: "gravestone-round", label: "the graves", x: 6, z: -4.5, rot: 0 },
      { id: "grave-11", piece: "grave", label: "the graves", x: 6, z: -3.2, rot: 0 },
      { id: "gravestone-round-12", piece: "gravestone-round", label: "the graves", x: -5, z: 0.5, rot: 0 },
      { id: "gravestone-bevel-13", piece: "gravestone-bevel", label: "the graves", x: -2.5, z: 0.5, rot: 0 },
      { id: "gravestone-cross-14", piece: "gravestone-cross", label: "the graves", x: 0, z: 0.5, rot: 0 },
      { id: "gravestone-broken-15", piece: "gravestone-broken", label: "the graves", x: 2.5, z: 0.5, rot: 0 },
      { id: "gravestone-bevel-16", piece: "gravestone-bevel", label: "the graves", x: 5, z: 0.5, rot: 0 },
      { id: "crypt-small-17", piece: "crypt-small", label: "the crypt", x: -7.5, z: 3.5, rot: 0 },
      { id: "crypt-small-roof-18", piece: "crypt-small-roof", label: "the crypt", x: -7.5, z: 3.5, rot: 0 },
      { id: "cross-column-19", piece: "cross-column", label: "the stone cross", x: 7, z: 3, rot: 0 },
      { id: "pine-20", piece: "pine", label: "the pines", x: -9, z: -5, rot: 0 },
      { id: "pine-crooked-21", piece: "pine-crooked", label: "the pines", x: 8.5, z: -5.5, rot: 0 },
      { id: "bench-damaged-22", piece: "bench-damaged", label: "the bench", x: 2, z: 4.5, rot: 180 },
      { id: "lantern-candle-23", piece: "lantern-candle", label: "the lantern", x: 0.2, z: 1.4, rot: 0 },
      { id: "iron-fence-border-gate-24", piece: "iron-fence-border-gate", label: "the gate", x: 0, z: 6.9, rot: 0 },
      { id: "iron-fence-border-25", piece: "iron-fence-border", label: "iron-fence-border", x: -8, z: 6.9, rot: 0 },
      { id: "iron-fence-border-26", piece: "iron-fence-border", label: "iron-fence-border", x: -6, z: 6.9, rot: 0 },
      { id: "iron-fence-border-27", piece: "iron-fence-border", label: "iron-fence-border", x: -4, z: 6.9, rot: 0 },
      { id: "iron-fence-border-28", piece: "iron-fence-border", label: "iron-fence-border", x: -2, z: 6.9, rot: 0 },
      { id: "iron-fence-border-29", piece: "iron-fence-border", label: "iron-fence-border", x: 2, z: 6.9, rot: 0 },
      { id: "iron-fence-border-30", piece: "iron-fence-border", label: "iron-fence-border", x: 4, z: 6.9, rot: 0 },
      { id: "iron-fence-border-31", piece: "iron-fence-border", label: "iron-fence-border", x: 6, z: 6.9, rot: 0 },
      { id: "iron-fence-border-32", piece: "iron-fence-border", label: "iron-fence-border", x: 8, z: 6.9, rot: 0 },
    ],
  },
];